/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Books_1: THREE.Mesh
    Books_2: THREE.Mesh
    Books_3: THREE.Mesh
    Books_4: THREE.Mesh
  }
  materials: {
    MatBook1: THREE.MeshStandardMaterial
    MatBook2: THREE.MeshStandardMaterial
    MatBook4: THREE.MeshStandardMaterial
    MatBook3: THREE.MeshStandardMaterial
  }
}

export function Books(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF(
    '/models/room6/books-transformed.glb'
  ) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='room6'>
        <group name='Books' position={[-2.03, 1.9, -1.42]} rotation={[0, 1.57, 0]} scale={4.92}>
          <mesh
            name='Books_1'
            castShadow
            receiveShadow
            geometry={nodes.Books_1.geometry}
            material={materials.MatBook1}
          />
          <mesh
            name='Books_2'
            castShadow
            receiveShadow
            geometry={nodes.Books_2.geometry}
            material={materials.MatBook2}
          />
          <mesh
            name='Books_3'
            castShadow
            receiveShadow
            geometry={nodes.Books_3.geometry}
            material={materials.MatBook4}
          />
          <mesh
            name='Books_4'
            castShadow
            receiveShadow
            geometry={nodes.Books_4.geometry}
            material={materials.MatBook3}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/room6/books-transformed.glb')
