/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BookShelves: THREE.Mesh
    BookShelf1: THREE.Mesh
    plant002: THREE.Mesh
    plant002_1: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['wood.005']: THREE.MeshStandardMaterial
    ['Christmas Green']: THREE.MeshStandardMaterial
  }
}

export function Bookshelves(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/room6/bookshelves-transformed.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BookShelves.geometry}
        material={materials.Wood}
        position={[-2.19, 1.83, -1.5]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.31, 0.07, 0.76]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BookShelf1.geometry}
          material={materials['Material.014']}
          position={[0.08, 12.62, -0.72]}
          rotation={[Math.PI, 0, 0]}
          scale={[-0.92, -1, -1]}
        />
        <group
          position={[-0.25, 13.62, -0.38]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[2.68, 29.68, 6.57]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.plant002.geometry}
            material={materials['wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.plant002_1.geometry}
            material={materials['Christmas Green']}
          />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/room6/bookshelves-transformed.glb')
