/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_cabinetBedDrawer002: THREE.Mesh
    Mesh_cabinetBedDrawer002_1: THREE.Mesh
    Mesh_door002: THREE.Mesh
    Mesh_door002_1: THREE.Mesh
    Mesh_drawer003: THREE.Mesh
    Mesh_drawer003_1: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    ['_defaultMat.001']: THREE.MeshStandardMaterial
    ['metal.003']: THREE.MeshStandardMaterial
  }
}

export function Cabinet(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/room6/cabinet-transformed.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.16, 0, -1.59]} scale={3.52}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_cabinetBedDrawer002.geometry}
          material={materials.Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_cabinetBedDrawer002_1.geometry}
          material={materials['_defaultMat.001']}
        />
        <group position={[0.02, 0.05, -0.01]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_door002.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_door002_1.geometry}
            material={materials['metal.003']}
          />
        </group>
        <group position={[0.02, 0.17, -0.16]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_drawer003.geometry}
            material={materials.Wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_drawer003_1.geometry}
            material={materials['metal.003']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/room6/cabinet-transformed.glb')
