/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Gift: THREE.Mesh
    BezierCircle001: THREE.Mesh
    Bow001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube005: THREE.Mesh
  }
  materials: {
    GiftBox: THREE.MeshStandardMaterial
    ['Christmas Green']: THREE.MeshStandardMaterial
  }
}

export function Gift(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/room6/gift-transformed.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gift.geometry}
        material={materials.GiftBox}
        position={[0.38, 1.09, -1.96]}
        scale={0.27}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle001.geometry}
          material={materials['Christmas Green']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bow001.geometry}
          material={materials['Christmas Green']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials['Christmas Green']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials['Christmas Green']}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/room6/gift-transformed.glb')
