export { Bed } from './bed'
export { Books } from './books'
export { Bookshelves } from './bookshelves'
export { Cabinet } from './cabinet'
export { Desk } from './desk'
export { Gift } from './gift'
export { Room } from './room'
export { Mug } from './mug'
